#Update credentials before new setup

# Supabase PostgreSQL Database Connection (Pooler)
spring.datasource.url=****
spring.datasource.username=*****
spring.datasource.password=*****
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Settings (Protects your Supabase tables)
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Twilio Verify API Credentials
twilio.account-sid=****
twilio.auth-token=****
twilio.verify-service-sid=****
