# Supabase PostgreSQL Database Connection (Pooler)
spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0
spring.datasource.username=postgres.lzphvudwlvzopdjkjoik
spring.datasource.password=bs563@snu.edu.in
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Settings (Protects your Supabase tables)
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Twilio Verify API Credentials
twilio.account-sid=ACd87e6ca280abed84ef9bcbc3931c939a
twilio.auth-token=3d6704c56b2e113ba583c2de3fc32b6c
twilio.verify-service-sid=VA4267ab32a0d9a9e46141597cc37254f4